# Generated by Django 4.1.3 on 2022-11-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='permission',
        ),
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('SUPERVISOR', 'supervisor'), ('CONTRIBUTOR', 'contributor'), ('AUTHOR', 'author')], max_length=256),
        ),
    ]
