# Generated by Django 4.1.3 on 2022-11-30 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='project',
        ),
        migrations.AddField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.issue'),
            preserve_default=False,
        ),
    ]
