# Generated by Django 4.1.3 on 2022-11-30 19:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_remove_comment_project_comment_issue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contributor',
            new_name='Collaborator',
        ),
    ]
