# Generated by Django 4.1.3 on 2022-11-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0003_rename_project_id_contributor_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='author',
        ),
        migrations.AddField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('OWNER', 'owner'), ('TEAM_MATE', 'teammate')], default='TEAM_MATE', max_length=256),
        ),
    ]
